# Generated by Django 4.2.5 on 2023-09-27 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Accounts', '0002_rename_user_id_userinfo_user'),
        ('Stores', '0004_alter_store_zip_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_date', models.DateTimeField()),
                ('destination', models.CharField(blank=True, max_length=100, null=True)),
                ('order_total', models.FloatField()),
                ('items', models.CharField(max_length=800)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.userinfo')),
                ('store_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Stores.store')),
            ],
        ),
    ]
