# Generated by Django 4.2.5 on 2023-09-27 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stores', '0002_store_city_store_state_alter_store_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='zip_code',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='store',
            name='city',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='store',
            name='state',
            field=models.CharField(max_length=20),
        ),
    ]
