# Generated by Django 4.2.5 on 2023-09-27 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stores', '0003_store_zip_code_alter_store_address_alter_store_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='zip_code',
            field=models.IntegerField(),
        ),
    ]
