# Generated by Django 4.2.5 on 2023-09-22 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0002_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_type', models.CharField(max_length=25)),
                ('first_name', models.CharField(max_length=35)),
                ('last_name', models.CharField(max_length=50)),
                ('email_address', models.CharField(blank=True, max_length=75, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('username', models.CharField(blank=True, max_length=30, null=True)),
                ('password', models.CharField(blank=True, max_length=30, null=True)),
                ('other_information', models.CharField(blank=True, max_length=1000, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('store_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Store.store')),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('shipment_id', models.AutoField(primary_key=True, serialize=False)),
                ('shipment_origin', models.CharField(max_length=70)),
                ('expected_date', models.DateField()),
                ('shipment_status', models.CharField(max_length=150)),
                ('shipment_tracking_history', models.CharField(max_length=1000)),
                ('shipment_tracking_link', models.CharField(blank=True, max_length=100, null=True)),
                ('destination_store_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.store')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('purchase_id', models.AutoField(primary_key=True, serialize=False)),
                ('purchase_date', models.DateTimeField()),
                ('purchase_total', models.FloatField()),
                ('items', models.CharField(max_length=800)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='Store.user')),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='Store.user')),
                ('store_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.store')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_date', models.DateTimeField()),
                ('destination', models.CharField(blank=True, max_length=100, null=True)),
                ('order_total', models.FloatField()),
                ('items', models.CharField(max_length=800)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.user')),
                ('store_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.store')),
            ],
        ),
    ]
