# Generated by Django 4.2.5 on 2023-09-27 05:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Stores', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('user_type', models.CharField(max_length=25)),
                ('first_name', models.CharField(max_length=35)),
                ('last_name', models.CharField(max_length=50)),
                ('email_address', models.CharField(blank=True, max_length=75, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('username', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('password', models.CharField(blank=True, max_length=30, null=True)),
                ('other_information', models.CharField(blank=True, max_length=1000, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('store_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Stores.store')),
            ],
        ),
    ]
