# Generated by Django 4.2.5 on 2023-09-27 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_rename_user_id_userinfo_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminInfo',
            fields=[
                ('userinfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Accounts.userinfo')),
            ],
            bases=('Accounts.userinfo',),
        ),
        migrations.CreateModel(
            name='CustomerInfo',
            fields=[
                ('userinfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Accounts.userinfo')),
            ],
            bases=('Accounts.userinfo',),
        ),
        migrations.CreateModel(
            name='EmployeeInfo',
            fields=[
                ('userinfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Accounts.userinfo')),
            ],
            bases=('Accounts.userinfo',),
        ),
        migrations.CreateModel(
            name='ManagerInfo',
            fields=[
                ('userinfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Accounts.userinfo')),
            ],
            bases=('Accounts.userinfo',),
        ),
    ]
