# Generated by Django 4.2.5 on 2023-09-27 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_admininfo_customerinfo_employeeinfo_managerinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='user_type',
        ),
    ]
