# Generated by Django 4.2.5 on 2023-09-27 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_remove_userinfo_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='email_address',
            field=models.CharField(blank=True, max_length=75, null=True, unique=True),
        ),
    ]
