# Generated by Django 4.2.5 on 2023-10-03 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0005_alter_userinfo_email_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='store_id',
            new_name='store_location',
        ),
    ]
