# Generated by Django 4.2.5 on 2023-10-03 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0006_rename_store_id_userinfo_store_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='store_location',
            new_name='store_id',
        ),
    ]
