# Generated by Django 4.2.5 on 2023-09-27 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_admininfo_customerinfo_employeeinfo_managerinfo'),
        ('Purchases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='manager_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manager', to='Accounts.managerinfo'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='Accounts.customerinfo'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='employee_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='Accounts.employeeinfo'),
        ),
    ]
